# Copyright 2020 Adam Chalkley
#
# https://github.com/atc0005/dnsc
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

name: Test local linting tools installation

# Run builds for Pull Requests (new, updated)
# `synchronized` seems to equate to pushing new commits to a linked branch
# (whether force-pushed or not)
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test_local_lint_tools_installation:
    name: Install linting tools via Makefile
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Set up Go
        # https://github.com/actions/setup-go
        uses: actions/setup-go@v2.1.1
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      # This could prove useful if we need to troubleshoot odd results and
      # tie them back to a specific version of Go
      - name: Print go version
        run: |
          go version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.1

      - name: Install Go linting tools
        run: |
          # add executables installed with go get to PATH
          # TODO: this will hopefully be fixed by
          # https://github.com/actions/setup-go/issues/14
          export PATH=${PATH}:$(go env GOPATH)/bin
          make lintinstall
