# Copyright 2020 Adam Chalkley
#
# https://github.com/atc0005/dnsc
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

name: Validate Codebase using Docker

# Run builds for Pull Requests (new, updated)
# `synchronized` seems to equate to pushing new commits to a linked branch
# (whether force-pushed or not)
on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint_code:
    name: Lint codebase
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: golangci/golangci-lint:v1.29

    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.1

      - name: Run golangci-lint using config file settings
        # use the `--exclude-use-default` flag for now until
        # we merge GH-72
        run: |
          pwd
          ls
          echo $GITHUB_WORKSPACE
          golangci-lint run -v --exclude-use-default
