# Copyright 2020 Adam Chalkley
#
# https://github.com/atc0005/dnsc
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

name: Validate Codebase

# Run builds for Pull Requests (new, updated)
# `synchronized` seems to equate to pushing new commits to a linked branch
# (whether force-pushed or not)
on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint_code:
    name: Lint codebase
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: golangci/golangci-lint:v1.29

    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.1

      - name: Run golangci-lint using repo-provided config file settings
        run: |
          # https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#workdir
          cd $GITHUB_WORKSPACE
          golangci-lint run -v

  test_code:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        go-version: ["1.13", "1.14", "rc"]

    container:
      image: golang:${{ matrix.go-version }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.1

      - name: Run all tests
        run: go test -mod=vendor -v ./...

  build_code:
    name: Build codebase
    runs-on: ${{ matrix.os }}
    # Default: 360 minutes
    timeout-minutes: 10
    strategy:
      matrix:
        go-version: ["1.13", "1.14", "rc"]

    container:
      image: golang:${{ matrix.go-version }}

    steps:
      - name: Print go version
        run: |
          go version

      - name: Check out code
        uses: actions/checkout@v2.3.1

      - name: Build using vendored dependencies
        run: go build -v -mod=vendor ./cmd/dnsc
