# Copyright 2020 Adam Chalkley
#
# https://github.com/atc0005/dnsc
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

name: Lint and Build using Makefile

# Run builds for Pull Requests (new, updated)
# `synchronized` seems to equate to pushing new commits to a linked branch
# (whether force-pushed or not)
on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint_code_with_makefile:
    name: Lint codebase using Makefile
    runs-on: ubuntu-latest
    # Default: 360 minutes
    timeout-minutes: 10

    steps:
      - name: Set up Go
        # https://github.com/actions/setup-go
        uses: actions/setup-go@v2.1.1
        with:
          go-version: 1.14
        id: go

      # This could prove useful if we need to troubleshoot odd results and
      # tie them back to a specific version of Go
      - name: Print go version
        run: go version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.1

      - name: Install Go linting tools
        run: make lintinstall

      - name: Run Go linting tools using project Makefile
        run: make linting

  build_code_with_makefile:
    name: Build codebase using Makefile
    runs-on: ubuntu-latest
    # Default: 360 minutes
    timeout-minutes: 10
    strategy:
      matrix:
        # Supported versions of Go
        go-version: [1.13.x, 1.14.x]

    steps:
      - name: Set up Go
        # https://github.com/actions/setup-go
        uses: actions/setup-go@v2.1.1
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      # This could prove useful if we need to troubleshoot odd results and
      # tie them back to a specific version of Go
      - name: Print go version
        run: go version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.1

      - name: Build using project Makefile
        run: make all
